// Copyright 2026 daniele-cruciani. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Job struct {
	Department  string `json:"department"`
	Description string `json:"description"`
	Id          string `json:"id"`
	JobType     string `json:"job_type"`
	Location    string `json:"location"`
	PostedAt    string `json:"posted_at"`
	Title       string `json:"title"`
	Url         string `json:"url"`
}
