// Copyright 2026 daniele-cruciani. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTwilioCareersJobsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "twilio-careers-jobs",
		Short: "Manage twilio careers jobs",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTwilioCareersJobsGetCmd(flags))
	cmd.AddCommand(newTwilioCareersJobsListCmd(flags))
	return cmd
}
